### ISSUE TITLE
Using requirejs and alternate version of ace issue.

### ISSUE THREAD

**Issue by SplicePHP** [prbaron/pbckcode#38]
I have modified the code a bit to allow ace to be loaded via requirejs instead of the cdn in the default system. I am getting a strange error and don't have any idea how to resolve it and thought you might  be able to help. Here is what is happening:
I load the requirejs instance of ace for another widget on my project.
After this ckeditor is also loaded via requirejs.
Then pbckcode is loaded via ckeditor.
The problem is that because ace is loaded before ckeditor the ace styles are overridden by .cke_reset_all *
I can't change the loading order of the stylesheets since ace is required before ckeditor and both libraries load their styles themselves.
This .cke_reset_all causes havoc with ace if the stylesheet of the skin is loaded after ace.
I am kind of stuck on this.
Any suggestion to resolve this issue would be appreciated.
Thanks.

**Comment by prbaron** [comment]
Hi !

> This .cke_reset_all causes havoc with ace if the stylesheet of the skin is loaded after ace.
Can't you override CSS using !important ?

**Comment by SplicePHP** [comment]
Hi, I resolved the problem I had.
What was happening is that the ace library was loaded before ckeditor's theme. CKEditor then overrided this generated css with its own styles due to the css being appended to the head. Since both ace and ckeditor generates the css at runtime "!important" was not an option. Important would also mess with the descendants.
Here is how I fixed my issue if anyone else has the same problem:

I commented out the default ace loader events in plugin.js and modified onLoad in pbckcode.js to look like this:

```
        onLoad: function () {
            dialog = this;
            var id = dialog.getContentElement('editor', 'code-textarea').getElement().getId();
            // we load the ACE plugin to our div
            aceEditor = ace.edit(id);
            // save the aceEditor into the editor object for the resize event
            editor.aceEditor = aceEditor;

            // set default settings
            aceEditor.setTheme("ace/theme/" + editor.settings.theme);
            aceEditor.setHighlightActiveLine(true);
            aceEditor.$blockScrolling = Infinity;

            aceSession = aceEditor.getSession();
            aceSession.setMode("ace/mode/" + editor.settings.modes[0][1]);
            aceSession.setTabSize(editor.settings.tab_size);
            aceSession.setUseSoftTabs(true);

            // load ace extensions
            whitespace = ace.require('ace/ext/whitespace');
            
            
            var editorId = dialog.getContentElement('editor').getElement().getId();
            $('#'+editorId).parents().eq(5).css('padding', '0px');
            require(['jquery'], function () {
                aceEditor.on('focus', function () {
                    var s2 = $('style#ace-tm');
                    if (s2.length !== 0) {
                        var s1 = s2.prev();
                        var s3 = s2.next();
                        s1.appendTo('head');
                        s2.appendTo('head');
                        s3.appendTo('head');
                    }
                });
            });

        },
```

What it does:
It looks for the ace style node and moves it after the ckeditor theme's style.
I know this is a bit of a dirty method of making this work but it does the trick.
