### ISSUE TITLE
Tab-Size select label didn't get its label value from the options.

### ISSUE THREAD

**Issue by eladcandroid** [prbaron/pbckcode#42]
Need to change /dialogs/pbckcode.js from

                        type      : 'select',
                        id        : 'code-tabsize-select',
                        className : 'cke_pbckcode_form',
                        label     : 'Tab Size',

to
                        type      : 'select',
                        id        : 'code-tabsize-select',
                        className : 'cke_pbckcode_form',
                        label     : editor.lang.pbckcode.tabSize,

**Comment by prbaron** [comment]
Thanks ! It's fixed.
