### ISSUE TITLE
No wrap <pre>

### ISSUE THREAD

**Issue by darkfriend** [prbaron/pbckcode#43]
How not wrap "pre"?

**Comment by prbaron** [comment]
Hi,

can you be more specific about your need ?

**Comment by darkfriend** [comment]
Hello.

I want the current code was inserted in the editor window. And when came back changed. But it is not wrapped in the pre tag. The result would be an ideal code editor.

**Comment by prbaron** [comment]
Do you want syntax highlighting in the ckeditor instance ?

-- 
Pierre BARON

**Comment by prbaron** [comment]
Closed as unclear. Feel free to reopen with more information.
