### ISSUE TITLE
When will this plugin be support 4.5?

### ISSUE THREAD

**Issue by anik786** [prbaron/pbckcode#44]
When will this plugin be support 4.5 as it is marked as unsupported here: http://ckeditor.com/addon/pbckcode

**Comment by prbaron** [comment]
The plugin is currently supporting 4.5 as it is supporting older versions of CKEditor

**Comment by anik786** [comment]
In that case how come this: http://ckeditor.com/addon/pbckcode does not have a tick on the 4.5 version.
Will it be possible to update it???

**Comment by prbaron** [comment]
This is not ticked because when I released the version, 4.5 was not out yet, so I did not have the possibility to tick it.

**Comment by anik786** [comment]
Is it possible to tick it now, or would this have to be delayed till the next version?

**Comment by prbaron** [comment]
I ticked it

-- 
Pierre BARON
