### ISSUE TITLE
Indentation is bugged on ace editor

### ISSUE THREAD

**Issue by Minizarbi** [prbaron/pbckcode#47]
Hi! When I try to indent code on the ace editor opened by the plugin, the cursor is correctly indented but the text is not.
If I save the code, the final code on ckeditor is correctly indented.
Like I write a function (assuming _ are spaces):
`function test() {`
*cursor is here*
`____|`
*but text is here*
`alert();____|`
*the cursor is right after ; but it is shown at the end of the line*
`}`
I have the problem on your demo site too, but the problem is not on the demo on ace editor.
I use Firefox (same bug on chrome) on KDE on Fedora 23, let me know if you see the bug too ;)

**Comment by Minizarbi** [comment]
Ok it seems it comes from the option show_hidden in ace editor:
https://ace.c9.io/build/kitchen-sink.html
Whe we don't show invisible the bug is not here anymore.

**Comment by prbaron** [comment]
Well spotted ! I will fix this ASAP.

Thanks !

**Comment by prbaron** [comment]
Fixed, thank you for spotting this !
