### ISSUE TITLE
Double quotes to Single quotes

### ISSUE THREAD

**Issue by Tomarnst** [prbaron/pbckcode#48]
When leaving the editor I get this:
`<pre data-pbcklang="html" data-pbcktabsize="4">
<code class="html ">some code here</code></pre>`

I have a problem on my front-end with the double quotes and need this:
`<pre data-pbcklang='html' data-pbcktabsize='4'>
<code class='html'>some code here</code></pre>`

Is there any way I can set the double quotes to single one's ?

**Comment by prbaron** [comment]
These double quotes are added by CKEditor when creating the right HTML from the plugin. I cannot change that unfortunately.

There may be a way to override this in CKEditor though.
